#theme: jekyll-theme-slate

#GitHub Pages supports the following themes:
#    Architect
#    Cayman
#    Dinky
#    Hacker
#    Leap day
#    Merlot
#    Midnight
#    Minima,It's Jekyll's default (and first) theme. It's what you get when you run jekyll new.
#    Minimal, theme: jekyll-theme-minimal ????
#    Modernist
#    Slate
#    Tactile
#    Time machine

#works
theme: minima
#theme: jekyll-theme-minimal

#does not work
#theme: minimal


#works

# does not work
#remote_theme: "daattali/beautiful-jekyll"
#remote_theme: "Gaohaoyang/gaohaoyang.github.io"


# not needed ?
url: "https://m040601.github.io/purejekyllgithubdefaults"
# needed
baseurl: "/purejekyllgithubdefaults"


# social links
twitter_username: todaviasomos
github_username:  m040601
rss: rss
# dribbble_username: jekyll
facebook_username: todaviasociacion
flickr_username: todaviasostenible
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
youtube_username: UCDf_rncabeuc7WcrzqqLCrg
# googleplus_username: +jekyll



description: > # this means to ignore newlines until "twitter_username:"
  If i leave "description" empty in config.yaml, it picks up the one frome github

